name: docker use cached img
on:
  pull_request:

jobs:
  use:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: docker-cache.yml
          name: myimage
          path: /tmp
      -
        name: Load Docker image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
